graphql:
  servlet:
    enabled: true
    mapping: /graphql
    cors-enabled: true
    cors:
      allowed-origins: "*"
      allowed-methods: GET, HEAD, POST, PUT
    exception-handlers-enabled: true
    context-setting: PER_REQUEST_WITH_INSTRUMENTATION
    async-mode-enabled: true
    max-query-depth: 50


redis:
  host: 112.196.108.244
  port: 6379
  database: 0
  timeout: 60
  password: CHuJukJQCrr23kLs
  cache:
    default:
      duration: 2400
    list:
      -
        name: userByName
        duration: 600


